name: docker

on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

jobs:
  docker-flang:
    runs-on: ubuntu-22.04
    env:
      TEST_TAG: verificarlo/verificarlo:test
      LATEST_TAG: ${{ github.repository }}:latest
      RELEASE_TAG: ${{ github.repository }}:${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "make -C /build/verificarlo installcheck"
      - name: Build and push
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.LATEST_TAG }}
            ${{ env.RELEASE_TAG }}

  docker:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu:24.04
            llvm: 17
            gcc: 9
          - os: ubuntu:24.04
            llvm: 18
            gcc: 9
          - os: ubuntu:24.04
            llvm: 19
            gcc: 9
          - os: ubuntu:24.04
            llvm: 20
            gcc: 9
    runs-on: ubuntu-22.04
    env:
      TEST_TAG: verificarlo/verificarlo:test-llvm-${{ matrix.llvm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            UBUNTU_VERSION=${{ matrix.os }}
            LLVM_VERSION=${{ matrix.llvm }}
            GCC_VERSION=${{ matrix.gcc }}
            WITH_FLANG=
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "make -C /build/verificarlo installcheck"
